# Generated by Django 3.0.2 on 2020-01-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avatar',
            field=models.ImageField(blank=True, default='blog_mages/img1.png', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_images/img1.png', upload_to='profile_images'),
        ),
    ]
